import assert from "node:assert/strict";
import { existsSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import test from "node:test";

import { CATALOG_LAYER_MANIFEST } from "../data/12.1/catalog-layer-manifest.js";
import { FERAL_SEMANTIC_PROVENANCE } from "../data/12.1/feral-semantic-provenance.js";
import {
  ACTION_CATALOG,
  APL_CATALOG,
  CUSTOM_HANDLER_DECLARATIONS,
  EFFECT_CATALOG,
  INTERNAL_ACTION_CATALOG,
  SET_BONUS_CATALOG,
  TALENT_EFFECT_COVERAGE,
} from "../data/12.1/feral-game-data.js";
import {
  EQUIPMENT_EFFECT_IMPLEMENTATIONS,
  EQUIPMENT_STATIC_MODIFIER_CATALOG,
  ITEM_ACTION_CATALOG,
  ITEM_EFFECT_CATALOG,
} from "../data/12.1/feral-item-effect-data.js";

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const dataRoot = resolve(projectRoot, "demo/data/12.1");

async function assertFacadeIdentity(facadePath, layeredPath) {
  const [facade, layered] = await Promise.all([import(facadePath), import(layeredPath)]);
  assert.deepEqual(Object.keys(facade).sort(), Object.keys(layered).sort());
  for (const name of Object.keys(facade)) assert.strictEqual(facade[name], layered[name], `${name} must be the same export`);
}

test("catalog manifest separates generated facts from authored semantics and every declared path exists", async () => {
  assert.equal(CATALOG_LAYER_MANIFEST.schemaVersion, 1);
  assert.equal(CATALOG_LAYER_MANIFEST.generated.length, 4);
  assert.equal(CATALOG_LAYER_MANIFEST.authored.length, 6);
  assert.equal(CATALOG_LAYER_MANIFEST.dependencyRules.generatedMayImportAuthored, false);
  assert.equal(CATALOG_LAYER_MANIFEST.dependencyRules.uiMayReadLayerInternalsDirectly, false);
  assert.equal(CATALOG_LAYER_MANIFEST.dependencyRules.controllerMayReadLayerInternalsDirectly, false);
  assert.equal(CATALOG_LAYER_MANIFEST.dependencyRules.unsupportedMustRemainStructured, true);

  for (const entry of [...CATALOG_LAYER_MANIFEST.generated, ...CATALOG_LAYER_MANIFEST.authored]) {
    assert.equal(existsSync(resolve(dataRoot, entry.module)), true, `${entry.module} must exist`);
  }
  for (const entry of CATALOG_LAYER_MANIFEST.generated) {
    assert.equal(existsSync(resolve(projectRoot, entry.generatedBy)), true, `${entry.generatedBy} must exist`);
    for (const source of entry.sources) {
      if (source === "SIMC_BIN") continue;
      assert.equal(existsSync(resolve(projectRoot, source)), true, `${source} must exist`);
    }
  }
});

test("generated modules are generator-owned, cannot import authored semantics, and generators target the generated layer", async () => {
  for (const entry of CATALOG_LAYER_MANIFEST.generated) {
    const moduleSource = await readFile(resolve(dataRoot, entry.module), "utf8");
    assert.match(moduleSource, /^\/\/ Generated by scripts\//, `${entry.module} must carry its generated header`);
    assert.doesNotMatch(moduleSource, /(?:from\s+|import\s*)["'][^"']*authored\//, `${entry.module} cannot import authored data`);

    const generatorSource = await readFile(resolve(projectRoot, entry.generatedBy), "utf8");
    assert.match(generatorSource, new RegExp(`demo/data/12\\.1/generated/${entry.module.split("/").at(-1).replaceAll(".", "\\.")}`));
  }
});

test("legacy catalog paths are behavior-free compatibility facades with identical exports", async () => {
  for (const facade of CATALOG_LAYER_MANIFEST.compatibilityFacades) {
    const source = await readFile(resolve(dataRoot, facade), "utf8");
    assert.doesNotMatch(source, /\b(?:const|let|var|function|class)\b/, `${facade} cannot define behavior or data`);
    assert.doesNotMatch(source, /^\s*import\b/m, `${facade} cannot import then transform data`);
    assert.match(source, /\bexport\b/, `${facade} must re-export the layered module`);
  }

  await assertFacadeIdentity("../data/12.1/feral-game-data.js", "../data/12.1/authored/feral-game-data.js");
  await assertFacadeIdentity("../data/12.1/feral-apl-ir.js", "../data/12.1/authored/feral-apl-ir.js");
  await assertFacadeIdentity("../data/12.1/feral-item-effect-data.js", "../data/12.1/authored/feral-item-effect-data.js");
  await assertFacadeIdentity("../data/12.1/feral-stat-data.js", "../data/12.1/authored/feral-stat-data.js");
  await assertFacadeIdentity("../data/12.1/build-fixtures.js", "../data/12.1/authored/build-fixtures.js");
  await assertFacadeIdentity("../data/12.1/version.generated.js", "../data/12.1/generated/version.generated.js");
  await assertFacadeIdentity("../data/12.1/druid-talent-tree.generated.js", "../data/12.1/generated/druid-talent-tree.generated.js");
  await assertFacadeIdentity("../data/12.1/feral-tier-sets.generated.js", "../data/12.1/generated/feral-tier-sets.generated.js");
  await assertFacadeIdentity("../data/12.1/simc-oracle-catalog.generated.js", "../data/12.1/generated/simc-oracle-catalog.generated.js");
  await assertFacadeIdentity("../data/12.1/feral-semantic-provenance.js", "../data/12.1/authored/feral-semantic-provenance.js");
  await assertFacadeIdentity("../data/12.1/catalog-layer-manifest.js", "../data/12.1/authored/catalog-layer-manifest.js");
});

test("UI and InteractiveController depend on stable facades rather than layer internals", async () => {
  for (const relativePath of ["demo/app.js", "demo/trainer-controller.js", "demo/core/interactive-controller.js"]) {
    const source = await readFile(resolve(projectRoot, relativePath), "utf8");
    assert.doesNotMatch(source, /data\/12\.1\/(?:authored|generated)\//, `${relativePath} cannot read layer internals directly`);
  }
});

test("every authored runtime rule has versioned provenance, identifiers, evidence precision and verification tests", () => {
  const expectedCount =
    SET_BONUS_CATALOG.length +
    ACTION_CATALOG.length +
    INTERNAL_ACTION_CATALOG.length +
    EFFECT_CATALOG.length +
    Object.keys(TALENT_EFFECT_COVERAGE).length +
    APL_CATALOG.length +
    CUSTOM_HANDLER_DECLARATIONS.length +
    ITEM_ACTION_CATALOG.length +
    ITEM_EFFECT_CATALOG.length +
    EQUIPMENT_EFFECT_IMPLEMENTATIONS.length +
    EQUIPMENT_STATIC_MODIFIER_CATALOG.length;
  assert.equal(FERAL_SEMANTIC_PROVENANCE.records.length, expectedCount);

  const ids = new Set();
  for (const record of FERAL_SEMANTIC_PROVENANCE.records) {
    assert.equal(ids.has(record.ruleId), false, `${record.ruleId} must be unique`);
    ids.add(record.ruleId);
    assert.match(record.sourceVersion.gameVersion, /^12\.1\./);
    assert.ok(record.sourceVersion.simcVersion);
    assert.match(record.sourceVersion.simcCommit, /^[0-9a-f]{40}$/);
    assert.ok(record.sourceRefs.length > 0, `${record.ruleId} must have source evidence`);
    assert.ok(["explicit", "catalog-default"].includes(record.evidencePrecision));
    assert.ok(record.verifiedBy.length > 0, `${record.ruleId} must name verification tests`);
    for (const testPath of record.verifiedBy) {
      assert.equal(existsSync(resolve(projectRoot, testPath)), true, `${record.ruleId} references missing ${testPath}`);
    }
  }

  const coverageRecords = FERAL_SEMANTIC_PROVENANCE.records.filter((record) => record.catalog === "talentCoverage");
  assert.equal(coverageRecords.length, Object.keys(TALENT_EFFECT_COVERAGE).length);
  for (const record of coverageRecords) {
    assert.ok(record.identifiers.talents.some((talent) => talent.token === record.catalogId));
    for (const talent of record.identifiers.talents) {
      assert.equal(talent.unresolved, undefined, `${talent.token} must resolve a generated Talent ID`);
      assert.ok(talent.entryId > 0);
      assert.ok(talent.spellId > 0);
    }
  }
});

test("unsupported talent and equipment mechanisms remain structured after the layer split", () => {
  for (const [token, coverage] of Object.entries(TALENT_EFFECT_COVERAGE)) {
    if (["unsupported", "out_of_scope"].includes(coverage.status)) {
      assert.ok(coverage.mechanism, `${token} must name its unsupported mechanism`);
      assert.ok(coverage.reason, `${token} must explain why it is unsupported`);
      assert.ok(coverage.impact, `${token} must describe the impact`);
    }
    if (coverage.status === "partially_supported") {
      assert.ok(coverage.unsupported?.mechanism, `${token} must structure the remaining mechanism`);
      assert.ok(coverage.unsupported?.reason, `${token} must explain the remaining mechanism`);
      assert.ok(coverage.unsupported?.impact, `${token} must describe the remaining impact`);
    }
  }

  for (const implementation of EQUIPMENT_EFFECT_IMPLEMENTATIONS) {
    if (["partially-supported", "out-of-scope"].includes(implementation.status)) {
      assert.ok(implementation.unsupportedEffects?.length > 0, `${implementation.sourceKind}:${implementation.sourceId} must remain structured`);
      for (const effect of implementation.unsupportedEffects) {
        assert.ok(effect.id && effect.mechanism && effect.reason && effect.impact);
      }
    }
  }
});
