import { createHash } from "node:crypto";
import {
  existsSync,
  readFileSync,
  readdirSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { join, relative } from "node:path";

export const BROWSER_RELEASE_SCHEMA_VERSION = 1;
export const DEPLOYED_SITE_FILES = Object.freeze([
  "index.html",
  "wow-hud.css",
  "reference-layout.css",
  "app.js",
  "feral-catalog.js",
  "feral-engine.js",
  "trainer-controller.js",
]);
export const DEPLOYED_SITE_DIRECTORIES = Object.freeze(["apl", "assets", "core", "data", "runtime"]);

const GENERATED_RELEASE_FILES = new Set(["index.html", "release.json", "release.generated.js"]);
const IMAGE_EXTENSIONS = new Set([".jpg", ".jpeg", ".png", ".gif", ".webp", ".svg"]);

function normalizePath(path) {
  return path.replaceAll("\\", "/");
}

function sha256Buffer(buffer) {
  return createHash("sha256").update(buffer).digest("hex");
}

function sha256File(path) {
  return sha256Buffer(readFileSync(path));
}

function collectDirectoryFiles(root, current, output) {
  for (const entry of readdirSync(current, { withFileTypes: true })
    .sort((left, right) => left.name.localeCompare(right.name))) {
    const absolutePath = join(current, entry.name);
    if (entry.isDirectory()) collectDirectoryFiles(root, absolutePath, output);
    else output.push(normalizePath(relative(root, absolutePath)));
  }
}

export function collectDeployedSiteFiles(demoRoot) {
  const files = [];
  for (const path of DEPLOYED_SITE_FILES) {
    if (!existsSync(join(demoRoot, path))) throw new Error(`Missing deployed browser file '${path}'`);
    files.push(path);
  }
  for (const path of DEPLOYED_SITE_DIRECTORIES) {
    const directory = join(demoRoot, path);
    if (!existsSync(directory)) throw new Error(`Missing deployed browser directory '${path}'`);
    collectDirectoryFiles(demoRoot, directory, files);
  }
  return [...new Set(files.map(normalizePath))].sort();
}

function extension(path) {
  const index = path.lastIndexOf(".");
  return index < 0 ? "" : path.slice(index).toLowerCase();
}

function resourceGroup(path) {
  if (path.startsWith("assets/icons/") && IMAGE_EXTENSIONS.has(extension(path))) return "icon";
  if (path.startsWith("apl/") || /(?:^|\/)feral-apl-ir\.js$/.test(path)) return "apl";
  if (path.startsWith("data/")) return "catalog";
  return "runtime";
}

function combinedHash(resources) {
  const canonical = resources
    .sort((left, right) => left.path.localeCompare(right.path))
    .map((resource) => `${resource.path}\0${resource.sha256}\n`)
    .join("");
  return sha256Buffer(canonical);
}

function replaceGeneratedBlock(source, marker, content) {
  const start = `<!-- ${marker}:start -->`;
  const end = `<!-- ${marker}:end -->`;
  const pattern = new RegExp(`${start}[\\s\\S]*?${end}`);
  if (!pattern.test(source)) throw new Error(`index.html is missing generated block '${marker}'`);
  return source.replace(pattern, `${start}\n${content}\n    ${end}`);
}

function browserReleaseModule(metadata, resourceHashes) {
  return `// Generated by scripts/generate-browser-release.mjs. Do not edit manually.\n` +
    `export const BROWSER_RELEASE = Object.freeze(${JSON.stringify(metadata, null, 2)});\n\n` +
    `export const BROWSER_RESOURCE_HASHES = Object.freeze(${JSON.stringify(resourceHashes, null, 2)});\n\n` +
    `export function versionedAssetUrl(path) {\n` +
    `  if (typeof path !== "string") return path;\n` +
    `  const normalized = path.replace(/^\\.\\//, "").split("?", 1)[0];\n` +
    `  const hash = BROWSER_RESOURCE_HASHES[normalized];\n` +
    `  return hash ? \`\${path.split("?", 1)[0]}?h=\${hash}\` : path;\n` +
    `}\n`;
}

function resourceRecord(demoRoot, path, group = resourceGroup(path)) {
  const absolutePath = join(demoRoot, path);
  return {
    path,
    group,
    bytes: statSync(absolutePath).size,
    sha256: sha256File(absolutePath),
  };
}

function validateReleaseArguments({ releaseId, createdAt, version }) {
  if (!/^[A-Za-z0-9._-]+$/.test(releaseId)) throw new Error(`Invalid browser releaseId '${releaseId}'`);
  if (!Number.isFinite(Date.parse(createdAt))) throw new Error(`Invalid browser release createdAt '${createdAt}'`);
  if (!/^12\.1\.\d+\.\d+$/.test(version.wowVersion)) throw new Error("Browser release requires a full WoW version");
  if (!Number.isInteger(version.wowBuild)) throw new Error("Browser release requires an integer WoW build");
  if (!/^[0-9a-f]{40}$/.test(version.simcCommit)) throw new Error("Browser release requires a full SimC commit");
  if (!Number.isInteger(version.profileCacheSchemaVersion)) {
    throw new Error("Browser release requires profileCacheSchemaVersion");
  }
}

export function writeBrowserRelease({ demoRoot, releaseId, createdAt, version }) {
  validateReleaseArguments({ releaseId, createdAt, version });
  const deployedFiles = collectDeployedSiteFiles(demoRoot)
    .filter((path) => !GENERATED_RELEASE_FILES.has(path));
  const baseResources = deployedFiles.map((path) => resourceRecord(demoRoot, path));
  const byGroup = (group) => baseResources.filter((resource) => resource.group === group);
  const runtimeHash = combinedHash(byGroup("runtime"));
  const catalogHash = combinedHash(byGroup("catalog"));
  const aplHash = combinedHash(byGroup("apl"));
  const iconManifestHash = combinedHash(byGroup("icon"));
  const metadata = {
    releaseId,
    schemaVersion: BROWSER_RELEASE_SCHEMA_VERSION,
    gameVersion: version.wowVersion,
    gameBuild: version.wowBuild,
    simcCommit: version.simcCommit,
    runtimeHash,
    catalogHash,
    aplHash,
    iconManifestHash,
    minimumCompatibleProfileSchema: version.profileCacheSchemaVersion,
    profileCacheNamespace:
      `${version.profileCacheNamespace}:p${version.profileCacheSchemaVersion}:${catalogHash.slice(0, 12)}`,
    createdAt,
  };
  const baseResourceHashes = Object.fromEntries(baseResources.map((resource) => [resource.path, resource.sha256]));
  writeFileSync(
    join(demoRoot, "release.generated.js"),
    browserReleaseModule(metadata, baseResourceHashes),
    "utf8",
  );

  const resources = [
    ...baseResources,
    resourceRecord(demoRoot, "release.generated.js", "metadata"),
  ].sort((left, right) => left.path.localeCompare(right.path));
  const resourceHashes = Object.fromEntries(resources.map((resource) => [resource.path, resource.sha256]));
  const importMap = {
    imports: Object.fromEntries(resources
      .filter((resource) => resource.path.endsWith(".js"))
      .map((resource) => [`./${resource.path}`, `./${resource.path}?h=${resource.sha256}`])),
  };

  let indexSource = readFileSync(join(demoRoot, "index.html"), "utf8");
  indexSource = replaceGeneratedBlock(indexSource, "release-styles", ["wow-hud.css", "reference-layout.css"]
    .map((path) => `    <link rel="stylesheet" href="./${path}?h=${resourceHashes[path]}" />`)
    .join("\n"));
  indexSource = replaceGeneratedBlock(
    indexSource,
    "release-import-map",
    `    <script type="importmap">\n${JSON.stringify(importMap, null, 2)
      .split("\n").map((line) => `      ${line}`).join("\n")}\n    </script>`,
  );
  indexSource = replaceGeneratedBlock(
    indexSource,
    "release-entry",
    `    <script type="module" src="./app.js?h=${resourceHashes["app.js"]}"></script>`,
  );
  writeFileSync(join(demoRoot, "index.html"), indexSource, "utf8");

  const release = {
    ...metadata,
    cachePolicy: {
      indexAndManifest: "no-cache",
      hashedResources: "public, max-age=31536000, immutable",
      serviceWorker: false,
    },
    resources,
  };
  writeFileSync(join(demoRoot, "release.json"), `${JSON.stringify(release, null, 2)}\n`, "utf8");
  return release;
}
